# https://github.com/anothrNick/github-tag-action
name: Bump version
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag (main)
      uses: anothrNick/github-tag-action@1.51.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        PRERELEASE: true
        VERBOSE: true
